hipchat:
  checkout_complete:
    enabled: no
  member_registration:
    enabled: no

slack:
  checkout_complete:
    enabled: no
  member_registration:
    enabled: no

asana:
  checkout_complete:
    enabled: no
  member_registration:
    enabled: no
